name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - name: Set up environment
      run: bundle install

    - name: Build
      run: bundle exec rake package
